volumes:
  orderer.main.chains:
  peer.main.chains:
  orderer.slim.plaschains:
  peer.slim.plaschains:

networks:
  chains:
    name: chains
  plaschains:
    name: plaschains

services:
  orderer.main.chains:
    container_name: orderer.main.chains
    image: hyperledger/fabric-orderer:latest
    mem_limit: 2g
    cpus: '2.0'
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8001
      - ORDERER_GENERAL_LOCALMSPID=mainchainsMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:8201
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.main.chains:8101
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../../../certs/plasma/ordererOrganizations/main.chains/orderers/orderer.main.chains/msp:/var/hyperledger/orderer/msp
      - ../../../certs/plasma/ordererOrganizations/main.chains/orderers/orderer.main.chains/tls:/var/hyperledger/orderer/tls
      - orderer.main.chains:/var/hyperledger/production/orderer
    ports:
      - 8001:8001
      - 8101:8101
      - 8201:8201
    networks:
      - chains

  peer.main.chains:
    container_name: peer.main.chains
    mem_limit: 4g
    cpus: '4.0'
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer.main.chains
      - CORE_PEER_ADDRESS=peer.main.chains:5001
      - CORE_PEER_LISTENADDRESS=0.0.0.0:5001
      - CORE_PEER_CHAINCODEADDRESS=peer.main.chains:5101
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:5101
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer.main.chains:5001
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer.main.chains:5001
      - CORE_PEER_LOCALMSPID=mainchainsMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer.main.chains:5201
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peermainchains"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../../../certs/plasma/peerOrganizations/main.chains/peers/peer.main.chains:/etc/hyperledger/fabric
      - peer.main.chains:/var/hyperledger/production
      # - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 5001:5001
      - 5101:5101
      - 5201:5201
    networks:
      - plaschains
      - chains

  orderer.slim.plaschains:
    container_name: orderer.slim.plaschains
    image: hyperledger/fabric-orderer:latest
    mem_limit: 2g
    cpus: '2.0'
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7001
      - ORDERER_GENERAL_LOCALMSPID=plaschainsMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7201
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.slim.plaschains:7101
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../../../certs/plasma/ordererOrganizations/slim.plaschains/orderers/orderer.slim.plaschains/msp:/var/hyperledger/orderer/msp
      - ../../../certs/plasma/ordererOrganizations/slim.plaschains/orderers/orderer.slim.plaschains/tls:/var/hyperledger/orderer/tls
      - orderer.slim.plaschains:/var/hyperledger/production/orderer
    ports:
      - 7001:7001
      - 7101:7101
      - 7201:7201
    networks:
      - plaschains

  peer.slim.plaschains:
    container_name: peer.slim.plaschains
    mem_limit: 4g
    cpus: '4.0'
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer.slim.plaschains
      - CORE_PEER_ADDRESS=peer.slim.plaschains:6001
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6001
      - CORE_PEER_CHAINCODEADDRESS=peer.slim.plaschains:6101
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6101
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer.slim.plaschains:6001
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer.slim.plaschains:6001
      - CORE_PEER_LOCALMSPID=plaschainsMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer.slim.plaschains:6201
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peerslimplaschains"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - ../../../certs/plasma/peerOrganizations/slim.plaschains/peers/peer.slim.plaschains:/etc/hyperledger/fabric
      - peer.slim.plaschains:/var/hyperledger/production
      # - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /root
    command: peer node start
    ports:
      - 6001:6001
      - 6101:6101
      - 6201:6201
    networks:
      - plaschains